"""Maturity reporters: MATURITY.md and audit.json generation."""

from __future__ import annotations

import json
import logging
from collections import Counter
from typing import TYPE_CHECKING

from .gaps import ALL_GAP_CODES, PENALTY_TABLE, Severity
from .scoring import RepoScore, tier_emoji

if TYPE_CHECKING:
    from ..config import ConvertConfig

logger = logging.getLogger(__name__)


def generate_maturity_md(repo_score: RepoScore, config: ConvertConfig) -> str:
    """Generate MATURITY.md report with repo score, gap distribution, worst/best systems."""
    lang = getattr(config, 'language', 'en')
    lines: list[str] = []

    emoji = tier_emoji(repo_score.tier)
    tier_label = repo_score.tier.upper()

    if lang == 'ru':
        lines.append('# Отчёт зрелости архитектурной модели')
        lines.append('')
        lines.append(f'**Общий балл**: {emoji} {repo_score.score}/100 ({tier_label})')
        lines.append(f'**Всего пробелов**: {repo_score.total_gaps}')
        lines.append(f'**Блокеров**: {repo_score.blocker_count}')
        lines.append(f'**Систем**: {len(repo_score.system_scores)}')
    else:
        lines.append('# Architecture Model Maturity Report')
        lines.append('')
        lines.append(f'**Repository score**: {emoji} {repo_score.score}/100 ({tier_label})')
        lines.append(f'**Total gaps**: {repo_score.total_gaps}')
        lines.append(f'**Blockers**: {repo_score.blocker_count}')
        lines.append(f'**Systems**: {len(repo_score.system_scores)}')

    lines.append('')

    total = len(repo_score.system_scores) or 1
    _render_tier_distribution(lines, repo_score, lang, total)
    _render_gap_distribution(lines, repo_score, lang, total)
    _render_worst_best(lines, repo_score, lang)

    lines.append('---')
    lines.append('*Generated by [archi2likec4](https://github.com/Lenivvenil/archi2likec4)*')
    lines.append('')
    return '\n'.join(lines)


def _render_tier_distribution(
    lines: list[str], repo_score: RepoScore, lang: str, total: int,
) -> None:
    """Render tier distribution table."""
    tier_counts: Counter[str] = Counter()
    for ss in repo_score.system_scores:
        tier_counts[ss.tier] += 1

    lines.append('## Распределение по уровням' if lang == 'ru' else '## Tier Distribution')
    lines.append('')
    lines.append('| Tier | Count | % |')
    lines.append('|------|-------|---|')
    for tier_name in ('complete', 'partial', 'skeletal', 'stub'):
        cnt = tier_counts.get(tier_name, 0)
        pct = round(cnt / total * 100)
        e = tier_emoji(tier_name)
        lines.append(f'| {e} {tier_name} | {cnt} | {pct}% |')
    lines.append('')


def _render_gap_distribution(
    lines: list[str], repo_score: RepoScore, lang: str, total: int,
) -> None:
    """Render gap distribution table."""
    gap_counter: Counter[str] = Counter()
    for ss in repo_score.system_scores:
        for g in ss.gaps:
            gap_counter[g.code] += 1

    lines.append('## Распределение пробелов' if lang == 'ru' else '## Gap Distribution')
    lines.append('')
    lines.append('| Code | Severity | Penalty | Count | % systems |')
    lines.append('|------|----------|---------|-------|-----------|')
    for code in ALL_GAP_CODES:
        cnt = gap_counter.get(code, 0)
        if cnt == 0:
            continue
        penalty = PENALTY_TABLE.get(code, 0)
        pct = round(cnt / total * 100)
        sev = _severity_for_code(code)
        lines.append(f'| {code} | {sev} | -{penalty} | {cnt} | {pct}% |')
    lines.append('')


def _render_worst_best(lines: list[str], repo_score: RepoScore, lang: str) -> None:
    """Render worst 10 and best 10 system tables."""
    sorted_scores = sorted(repo_score.system_scores, key=lambda s: s.score)
    worst = sorted_scores[:10]
    if worst:
        lines.append('## Худшие 10 систем' if lang == 'ru' else '## Worst 10 Systems')
        lines.append('')
        lines.append('| System | Score | Tier | Gaps |')
        lines.append('|--------|-------|------|------|')
        for ss in worst:
            e = tier_emoji(ss.tier)
            gap_codes = ', '.join(sorted({g.code for g in ss.gaps})) or '-'
            lines.append(f'| {ss.system_name} | {ss.score} | {e} {ss.tier} | {gap_codes} |')
        lines.append('')

    best = sorted(repo_score.system_scores, key=lambda s: -s.score)[:10]
    if best and best[0].score > 0:
        lines.append('## Лучшие 10 систем' if lang == 'ru' else '## Best 10 Systems')
        lines.append('')
        lines.append('| System | Score | Tier |')
        lines.append('|--------|-------|------|')
        for ss in best:
            e = tier_emoji(ss.tier)
            lines.append(f'| {ss.system_name} | {ss.score} | {e} {ss.tier} |')
        lines.append('')


def generate_maturity_json(repo_score: RepoScore) -> str:
    """Generate JSON maturity report for CI integration."""
    data = {
        'score': repo_score.score,
        'tier': repo_score.tier,
        'total_gaps': repo_score.total_gaps,
        'blocker_count': repo_score.blocker_count,
        'system_count': len(repo_score.system_scores),
        'systems': [
            {
                'id': ss.system_id,
                'name': ss.system_name,
                'score': ss.score,
                'tier': ss.tier,
                'gaps': [
                    {
                        'code': g.code,
                        'severity': g.severity,
                        'remediation': g.remediation,
                    }
                    for g in ss.gaps
                ],
            }
            for ss in sorted(repo_score.system_scores, key=lambda s: s.score)
        ],
    }
    return json.dumps(data, indent=2, ensure_ascii=False) + '\n'


def _severity_for_code(code: str) -> str:
    """Return severity label for a gap code."""
    blocker_codes = {'GAP-DEPLOY', 'GAP-ZONE', 'GAP-DUP', 'GAP-REF'}
    degraded_codes = {'GAP-INTEG', 'GAP-DOMAIN', 'GAP-SHALLOW', 'GAP-ENV'}
    if code in blocker_codes:
        return Severity.BLOCKER
    if code in degraded_codes:
        return Severity.DEGRADED
    return Severity.COSMETIC
