"""Generate CLAUDE.md for the target architecture repository."""

from __future__ import annotations

import logging

logger = logging.getLogger(__name__)


def generate_claude_md(domains: list[str], systems: list[str]) -> str:
    """Generate CLAUDE.md with conventions for the architecture repository.

    Parameters
    ----------
    domains:
        Sorted list of domain c4_ids present in the model.
    systems:
        Sorted list of system c4_ids present in the model.
    """
    domain_list = '\n'.join(f'  - `{d}`' for d in domains) if domains else '  (none)'
    system_count = len(systems)

    return f"""\
# Architecture Repository

Generated by [archi2likec4](https://github.com/Lenivvenil/archi2likec4).

## Structure
- `specification.c4` — Element kinds, tags, styles. Rarely changes.
- `infrastructure/` — Datacenter topology (zones, VMs). Shared across all systems.
- `domains/` — One file per domain. Declares systems (name + description).
- `systems/{{name}}/model.c4` — Subsystems via extend + outgoing relationships.
- `systems/{{name}}/deployment.c4` — extend VM with instanceOf + deployment views.
- `views/` — Cross-system views (landscape, domain contexts).

## Domains
{domain_list}

## Stats
- {system_count} systems across {len(domains)} domains

## Conventions
- Identifiers: snake_case, NO hyphens (LikeC4 parses `-` as minus).
- Each system has exactly `model.c4` + `deployment.c4`.
- System declared in `domains/{{domain}}.c4`, detailed via `extend`.
- Outgoing relationships go in `model.c4` of the SOURCE system.
- Deployment: `extend prod.{{dc}}.{{zone}}.{{vm}} {{ instanceOf ... }}`.
- Deployment views: targeted includes by VM paths, NO exclude.

## Add a system
1. `domains/{{domain}}.c4` — add `system {{id}} '{{Name}}' {{ ... }}`
2. Create `systems/{{id}}/model.c4` — `extend {{domain}}.{{id}} {{ components }}`
3. Create `systems/{{id}}/deployment.c4` — `extend prod.{{dc}}.{{zone}}.{{vm}} {{ instanceOf ... }}`

## Deploy to VM
1. Open `systems/{{name}}/deployment.c4`
2. Add `extend prod.{{dc}}.{{zone}}.{{vm}} {{ instanceOf {{domain}}.{{name}}.{{component}} }}`
3. Add `include prod.{{dc}}.{{zone}}.{{vm}}.**` to deployment view

## Add integration
1. Open `systems/{{source}}/model.c4`
2. Add `{{source_fqn}} -> {{target_fqn}} '{{description}}'`

## Commands
- `npx likec4 serve` — Live preview
- `npx likec4 build` — Validate all files
"""
